###测试注册接口
POST http://localhost:8080/register
Content-Type:  application/json

{
  "username":"huihuizi",
  "password":"123456"
}
###测试登录接口
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "huihuizi",
  "password": "123456"
}

### 不带 Token 访问受保护接口
POST http://localhost:8080/chat/send
Content-Type: application/json

{
  "content": "你好，我是硬闯的！"
}

### 携带 Token 访问受保护接口
POST http://localhost:8080/chat/send
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2F1dGgiLCJpYXQiOjE3NzUzODU5MzksImV4cCI6MTc3NTQ3MjMzOSwidXNlcklkIjoxLCJ1c2VybmFtZSI6Imh1aWh1aXppIn0.olcyvrcZ-JinvcT1v7IfoUyXVvz-aKhbB8YibtYzVeA

{
  "sessionId": 1,
  "content": "你好，AI！我已经拿到通行证了！"
}

###测试getHistoryByUserId方法
GET http://localhost:8080/

### 第二步：向大模型发射真正的对话！🚀
# 这一步将完整测试：拦截器鉴权 -> Controller接收 -> 存入User消息 -> 呼叫DeepSeek -> 存入AI消息 -> 返回前端
POST http://localhost:8080/chat/send
Content-Type: application/json
# 这里手动填入你刚刚获取到的 Token（注意 Bearer 后面有一个空格）
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2F1dGgiLCJpYXQiOjE3NzQ2OTM3MDcsImV4cCI6MTc3NDc4MDEwNywidXNlcklkIjoxLCJ1c2VybmFtZSI6Imh1aWh1aXppIn0.0naWmZGwJfsuGweou5Hfdff1tgE8KZabKWx_NtwGtHo

{
  "content": "你好，DeepSeek！我是第一次用我自己写的 Spring Boot 后端和你对话，这是我的毕业设计。请给我一句简短的鼓励吧！"
}

### 查询我的历史聊天记录 📖
# 这一步将完整测试：拦截器鉴权 -> Controller接收 -> 数据库查询 -> 列表反转 -> 返回前端
GET http://localhost:8080/chat/history
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX2F1dGgiLCJpYXQiOjE3NzQ2OTM3MDcsImV4cCI6MTc3NDc4MDEwNywidXNlcklkIjoxLCJ1c2VybmFtZSI6Imh1aWh1aXppIn0.0naWmZGwJfsuGweou5Hfdff1tgE8KZabKWx_NtwGtHo
